version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/home/ubuntu/grafana/prometheus/:/etc/prometheus"
      - "prometheus-data:/prometheus"
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - grafana-network

#  blackbox:
#    image: prom/blackbox-exporter:latest
#    privileged: true
#    volumes:
#      - /prometheus/blackbox.yaml:/etc/blackbox_exporter/config.yaml
#    ports:
#      - '9115:9115'
#    networks:
#      - grafana-network

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./prometheus/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'
    networks:
      - grafana-network
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - grafana-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
#      - ~/grafana-data-new:/var/lib/grafana
      - grafana-data-new:/var/lib/grafana
#      - ~/prometheus/grafana-data/:/var/lib/grafana
    restart: unless-stopped
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    networks:
      - grafana-network

  renderer:
    image: grafana/grafana-image-renderer:2.0.1
    container_name: grafana_renderer
    ports:
      - "8081:8081"
    environment:
      ENABLE_METRICS: 'true'
    networks:
      - grafana-network

  alertmanager:
    # Run Container as root user
    user: root
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: localhost
    restart: always
    ports:
      - '9093:9093'
   # Mount config file from local to Container
    volumes:
      - "/home/ubuntu/grafana/prometheus/:/etc/prometheus"
      - "alertmanager-data:/alertmanager/data"
   # Container start CMD to load config file
    command:
      - "--config.file=/etc/prometheus/alertmanager.yaml"
    networks:
      - grafana-network



networks:
  grafana-network:
    external: true

volumes:
  prometheus-data:
    driver: local
  grafana-data-new:
    driver: local
  alertmanager-data:
    driver: local
  influxdb_data:
    driver: local

